### ISSUE TITLE
Wrong HTTP path for AJAX request on data.json

### ISSUE THREAD

**Issue by sillevl** [DavidLejeune/lorawan-gps-mapper#20]
When showing the map on the production server, I get an error in the Javascript console: `GET http://localhost:3000/data.json net::ERR_CONNECTION_REFUSED` 

It seems the path for the ajax request is hardcoded into javascript. This needs to be solved by using a relative path.

> note !!! this bug is already solved on the server, but needs to be solved in code as well

**Comment by gsmman7** [comment]
this bug has been fixed by removing the localhost:3000 part from the code
