### ISSUE TITLE
Not all sensors show data

### ISSUE THREAD

**Issue by sillevl** [DavidLejeune/lorawan-gps-mapper#21]
Data from some sensors not shown on the map.

For example: Sensor with id 3 [http://gps-mapper.labict.be/sensors/3](http://gps-mapper.labict.be/sensors/3), shows no data on the map. If I check it on the server with the console, it has 1176 locations associated with that sensor:
```
Sensor.find(3).data.count
  Sensor Load (0.8ms)  SELECT  `sensors`.* FROM `sensors` WHERE `sensors`.`id` = 3 LIMIT 1
   (2.4ms)  SELECT COUNT(*) FROM `data` WHERE `data`.`sensor_id` = '3'
 => 1176
```

Sensor 1 seems to work correctly: [http://gps-mapper.labict.be/sensors/1 ](http://gps-mapper.labict.be/sensors/1)

**Comment by DavidLejeune** [comment]
Sensors only display data from the last 24 hours
